# Generated by Django 6.0.1 on 2026-01-22 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='post', max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.ImageField(upload_to='')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('UA', 'Unapproved'), ('PB', 'Published')], default='DF', max_length=2)),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=250)),
                ('tagSlug', models.SlugField(max_length=250)),
                ('tagType', models.CharField(default='General', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['tagSlug'],
                'indexes': [models.Index(fields=['tagSlug'], name='booru_tag_tagSlug_a1fa6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('pk', models.CompositePrimaryKey('image', 'tag', blank=True, editable=False, primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserBlacklist',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'tag', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booru.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'post', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='booru_post_publish_fbc740_idx'),
        ),
    ]
