# Generated by Django 6.0.1 on 2026-02-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='altText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to='booru\\static\\img'),
        ),
    ]
